name: Release project
on:
  push:
    tags-ignore:
      - "**"
  release:
    types:
      - created
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        versions: [ 17 ]
    runs-on: ubuntu-latest
    name: Release with Java ${{ matrix.versions }} projects
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.versions }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.versions }}
      - name: maven-settings-action
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: |
            [{
                "id": "github-validation",
                "username": "${{ github.actor }}",
                "password": "${{ secrets.GITHUB_TOKEN  }}"
            }]
      - name: Deploy projects
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_REGISTRY }}